config/routes.rb
Rails.application.routes.draw do
  
  get 'contact_form/new'

  get 'contact_form/create'

  devise_for :therapists, controllers: { sessions: 'therapists/sessions', registrations: 'therapists/registrations' }

  root 'pages#home'

  resources :profiles
  resources :appointments

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

	belongs_to :therapist, dependent: :destroy

end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :file,      :attachment => true

  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "your.email@your.domain.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base

	belongs_to :therapist, dependent: :destroy

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	def self.search_profile(param)
		where('zip LIKE :q', q: param)
	end

end

app/models/therapist.rb
class Therapist < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_many :appointments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

	before_action :set_appointment, only: [:show, :destroy]
  before_action :correct_therapist, only: [:show, :destroy]
  before_action :authenticate_therapist!, only: [:index, :show]

  def index
    @appointments = Appointment.all
  end

  def show
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = current_therapist.build_profile(profile_params)
    if @profile.save
      current_therapist.profile = @profile
      redirect_to @profile, notice: 'Profile was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @profile.update(profile_params)
      redirect_to @profile, notice: 'Profile was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @profile.destroy
    redirect_to profiles_url
  end

  private

    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    def correct_therapist
      @profile = current_therapist.profile #.find_by(id: params[:id])
      redirect_to profiles_path, notice: "Not authorized to edit this profile." if @profile.nil?
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :address_one, :address_two, :city, :state, :zip, :email, :phone, :degree, :university, :therapeutic_style, :years_of_practice, :accepting_new_patients, :image)
    end

    def set_options_for_state
      @options_for_state = ["DC", "MD", "VA"]
    end

end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController 
	def new 
		@contact_form = ContactForm.new 
	end 

	def create 
		begin 
			@contact_form = ContactForm.new(params[:contact_form]) 
			@contact_form.request = request 

				if @contact_form.deliver 
					flash.now[:notice] = 'Thank you for your message!' 
				else 
					render :new 
				end 
		
		rescue ScriptError 
			flash[:error] = 'Sorry, this message appears to be spam and was not delivered.' 
		end 
	end 
end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :correct_therapist, only: [:edit, :update, :destroy]
  before_action :authenticate_therapist!, except: [:index, :show]
  before_action :set_options_for_state, only: [:new, :edit]


  def index
    # @profiles = Profile.all
    if params[:q]
      @profiles = Profile.search_profile(params[:q])
    else
      @profiles = Profile.all
    end 
  end

  def show
  end

  def new
    @profile = current_therapist.build_profile
  end

  def edit
  end

  def create
    @profile = current_therapist.build_profile(profile_params)
    if @profile.save
      current_therapist.profile = @profile
      redirect_to @profile, notice: 'Profile was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @profile.update(profile_params)
      redirect_to @profile, notice: 'Profile was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @profile.destroy
    redirect_to profiles_url
  end

  private

    def set_profile
      @profile = Profile.find(params[:id])
    end

    def correct_therapist
      @profile = current_therapist.profile #.find_by(id: params[:id])
      redirect_to profiles_path, notice: "Not authorized to edit this profile." if @profile.nil?
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :address_one, :address_two, :city, :state, :zip, :email, :phone, :degree, :university, :therapeutic_style, :years_of_practice, :accepting_new_patients, :image)
    end

    def set_options_for_state
      @options_for_state = ["DC", "MD", "VA"]
    end
end

app/controllers/therapists/registrations_controller.rb
class Therapists::RegistrationsController < Devise::RegistrationsController

	protected

  def after_sign_up_path_for(resource)
    '/profiles/new'
  end
end

app/controllers/therapists/sessions_controller.rb
class Therapists::SessionsController < Devise::SessionsController
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
    base_title = "Private Practice Pro"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/views/appointments/new.html.erb
<h1>Wassup!</h1>

app/views/contact_forms/create.html.erb
<h1>ContactForm#create</h1>
<p>Find me in app/views/contact_form/create.html.erb</p>

app/views/contact_forms/new.html.erb
<h1>Contact Form</h1>

<%= form_for @contact_form do |f| %>

	<div class="form-group">
	<%= f.input :name, class: "control-label" %><br />
	<%= f.input :email, class: "control-label" %><br />
	<%= f.input :message, :as => :text, class: "control-label" %><br />

  <p><%= f.submit "Submit" %></p>
 <% end %>

app/views/layouts/_footer.html.erb
<footer>
	<ul id="nav">
  	<li><a href="#">About</a></li>
  	<li><a href="#">FAQ</a></li>
  	<li><a href="#">Contact</a></li>
		<% if therapist_signed_in? %>
  	<li><%= link_to "Log Out", destroy_therapist_session_path, method: :delete  %></li>
  	<% end %>
	</ul>
</footer>

app/views/layouts/_header.html.erb
<header>
<%= link_to "Private Practice Pro", root_path, :id => 'name' %>
</header>

app/views/layouts/_header_bootstrap.html.erb
<%= favicon_link_tag 'favicon.ico' %>
<nav class="navbar navbar-default" role="navigation">
	<div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Private Practice Pro", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
      <% if therapist_signed_in? %>
			<li><%= link_to "Create Profile", new_profile_path %></li>
      <li><%= link_to "Edit Profile", edit_profile_path(current_therapist.profile) %></li>

      <li><%= link_to "Log out", destroy_therapist_session_path, method: :delete %></li>
			<% else %>
			<li><%= link_to "Sign up", new_therapist_registration_path %></li>
      <li><%= link_to "Sign in", new_therapist_session_path %></li>
			<% end %>
		</ul>
  </div><!-- /.navbar-collapse -->
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,300' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>
	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
	
	<%= yield %>
	
</body>
</html>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>
<div id="hero">
    <div id="veil">
      <div id="welcome">
        <p>I am a...</p>

	    	<%= link_to "Therapist", new_therapist_session_path, id: "therapist" %>

        <button id="patient">Patient</button>
          <div id="dialog" title="Find a Therapist">Enter your zipcode:<br>
          
            <%= form_tag(profiles_path, method: 'get') do %>
                <%= text_field :q, params[:q] %>
            <%= submit_tag('Search') %>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" src="js/jquery.js"></script>
<script type="text/javascript" src="js/jquery-ui.min.js"></script>
<script type="text/javascript">
  $( "#dialog" ).dialog({ autoOpen: false });
  $( "#patient" ).click(function() {
    $( "#dialog" ).dialog( "open" );
  });
</script>

app/views/pages/index.html.erb
<div class="jumbotron">
	<% if therapist_signed_in? %>
		<h1>You're logged in!</h1>
		<%= link_to "Log out", destroy_therapist_session_path, method: :delete %>
	<% else %>
		<h1>Welcome to Private Practice Pro!</h1>
		<p>Wassup!</p>
		<%= link_to "Sign in", new_therapist_session_path, class: "btn btn-primary btn-lg" %>
	<% end %>
</div>

app/views/profiles/_form.html.erb
<div id="wrapper">

	<%= form_for @profile, html: { multipart: true } do |f| %>

		<%= f.label :first_name, "First Name:", :input_html => { :id => 'email' } %><br />
		<%= f.text_field :first_name, autofocus: true %>
		
		<%= f.label :last_name, "Last Name:" %><br />
		<%= f.text_field :last_name %>

		<%= f.label :address_one, "Address One:" %><br />
		<%= f.text_field :address_one %>

		<%= f.label :address_two, "Address Two:" %><br />
		<%= f.text_field :address_two %>

		<%= f.label :city, "City:" %><br />
		<%= f.text_field :city %>

		<%= f.label :state, "State:" %><br />
		<%= f.select :state, @options_for_state, autofocus: true %>

		<%= f.label :zip, "Zipcode:" %><br />
		<%= f.text_field :zip %>

		<%= f.label :email, "Email:" %><br />
		<%= f.email_field :email %>

		<%= f.label :phone, "Phone Number:" %><br />
		<%= f.text_field :phone %>

</div>

<div class="heading"><div id="wrapper"><h3>About You</h3></div></div>

<div id="wrapper">

	  <%= f.label :image, "Upload a profile photo:" %>
	  <%= f.file_field :image %>

		<%= f.label :degree, "Degree:" %><br />
		<%= f.text_field :degree %>

		<%= f.label :university, "University:" %><br />
		<%= f.text_field :university %>

		<%= f.label :therapeutic_style, "Therapeutic Style:" %><br />
		<%= f.text_field :therapeutic_style %>

		<%= f.label :years_of_practice, "Years of Practice:" %><br />
		<%= f.text_field :years_of_practice %>

	  <p><%= f.submit "Save", class: "btn btn-primary btn-lg" %></p>
	
	<% end %>

</div>

app/views/profiles/edit.html.erb
<% provide(:title, 'Edit Profile') %>

<% if @profile.errors.any? %>
	<% @profile.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
<% end %>

<h2>Edit Profile</h2>
<p>Edit your profile below.</p>

<%= render partial: 'form' %>

app/views/profiles/index.html.erb
<% provide(:title, 'Therapist Profiles') %>
<h2>Find a Therapist</h2>
<p>Find a therapist by zip code.</p>
</div>

<% @profiles.each do |profile| %>

<div class="container">
<%= link_to image_tag(profile.image.url(:thumb)), profile %>
<strong>First Name: <%= profile.first_name %></strong></br>
<strong>Last Name: <%= profile.last_name %></strong></br>

<hr>

</div>
<% end %>

app/views/profiles/new.html.erb
<% provide(:title, 'Create Profile') %>

<div class="heading"><div id="wrapper"><h1>Therapist Profile Form</h1></div></div>

<div id="wrapper">

	<% if @profile.errors.any? %>
		<% @profile.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	<% end %>

	<p>Fill out the form below to register with us.</p>

</div>

<%= render partial: 'form' %>

app/views/profiles/show.html.erb
<% provide(:title, 'Profile') %>

<div id="contactinfo">
	<%= image_tag @profile.image.url(:medium), :id => "pic" %>
	<div id="basicinfo">
		<h1 class="first_name"><%= "#{@profile.first_name} #{@profile.last_name}, #{@profile.degree}"  %></h1>
		
		<h2>Therapeutic Style:</h2>
		<p id="tstyle"><%= "#{@profile.therapeutic_style}" %></p>

		<p class="newpt nopatient">Not accepting new patients</p>

		 <div id="addrblock">
      <p id="address_one"><%= "#{@profile.address_one}" %></p>
      <% if @profile.address_two != nil %>
      	<p id="address_two"><%= "#{@profile.address_two}" %></p>
      <% end %>
      <span id="city"><%= "#{@profile.city}, #{@profile.state} #{@profile.zip}" %></span>
    </div>

    <div id="contactbutton">
        <button id="contact">Contact Info</button>
        <div id="contact-text" title="Contact Information">
          <p><strong>Phone Number: </strong><br>
          	<%= link_to "#{@profile.phone}", "tel:#{@profile.phone}", :id => "phone" %>
          </p>
          <br>
          <p><strong>Email: </strong><br>
          	<%= mail_to "#{@profile.email}", "#{@profile.email}", :id => "email" %>
          </p>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
	</div>
	<div id="qualifications">
    <div class="heading">Qualifications</div>
    <div id="qualtxt">
      <strong>Years in Practice: </strong><span id="years"><%= "#{@profile.years_of_practice}"  %></span><br>
      <strong>School: </strong><span id="university"><%= "#{@profile.university}" %></span><br>
      <strong>Degree: </strong><span id="degree"><%= "#{@profile.degree}" %></span>
    </div>
    <div id="finances">
      <div class="heading">Finances</div>
        <div id="financetxt">
        <strong>Accepted Insurance Plans:</strong>
        <ul class="insurance">
          <li class="nav">Aetna</li>
          <li class="nav">Blue Cross</li>
          <li class="nav">Cigna</li>
          <li class="nav">Kaiser</li>
          <li class="nav">Medicare</li>
        </ul>
        </div>
    </div>
  </div>

app/views/therapists/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Already a member? Log in.", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Not a member yet? Sign up now.", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>